In [86]:
import pandas as pd
def isClass(string):
    for x in range(0,5):
        if(not string[x].isdigit()):
            return False
    return True
def isCourse(string):
    if(len(string)<2):
        return False
    x = 0
    if(";" in string):
        return False
    while(x<len(string) and not string[x].isdigit()):
        x = x+1
    if(x>2 and x<len(string)):
        for i in range(x,x+4):
            if(not string[i].isdigit()):
                return False
        if(string[1:3].isupper()):
            return True
    return False
def isDepartment(string):
    if (not (any(char.isdigit() for char in string))):
        if (string[:1] != " "):
            return True
    return False

In [87]:
courses = []
classes = []
f = open("RawCourseList.txt", "r")
last_course = "";
for string in f:
    if(isCourse(string)):
        last_course = string;
    elif(isClass(string)):
        courses.append(last_course)
        classes.append(string)

In [89]:
df = pd.DataFrame()
df['Courses'] = courses
df['Classes'] = classes
df

,Courses,Classes
0,AAS 1020 Introduction to African-American and...,10001 100Lecture (4)Wait List (2 / 199) 179 / ...
1,AAS 1020 Introduction to African-American and...,10006 101Discussion (0)Wait List (0 / 199) 20 ...
2,AAS 1020 Introduction to African-American and...,10005 102Discussion (0)Wait List (1 / 199) 21 ...
3,AAS 1020 Introduction to African-American and...,10004 103Discussion (0)Wait List (2 / 199) 19 ...
4,AAS 1020 Introduction to African-American and...,10003 104Discussion (0)Wait List (0 / 199) 20 ...
5,AAS 1020 Introduction to African-American and...,10007 105Discussion (0)Wait List (1 / 199) 20 ...
6,AAS 1020 Introduction to African-American and...,10002 106Discussion (0)Wait List (1 / 199) 20 ...
7,AAS 1020 Introduction to African-American and...,13095 107Discussion (0)Wait List (1 / 199) 20 ...
8,AAS 1020 Introduction to African-American and...,13096 108Discussion (0)Wait List (1 / 199) 19 ...
9,AAS 1020 Introduction to African-American and...,13097 109Discussion (0)Wait List (0 / 199) 20 ...
10,AAS 2224 Black Femininities and Masculinities...,11702 001SEM (3)Wait List (4 / 199) 20 / 20Lis...
11,AAS 2224 Black Femininities and Masculinities...,11922 002SEM (3)Wait List (11 / 199) 19 / 20Li...
12,AAS 2224 Black Femininities and Masculinities...,19474 003SEM (3)Wait List (2 / 199) 20 / 20Lis...
13,AAS 2559 New Course in African and African Am...,18124 001SEM (3)Open 35 / 50Tony PerryWe 3:30p...
14,AAS 2559 New Course in African and African Am...,18125 002SEM (3)Wait List (4 / 199) 20 / 20Sab...
15,"AAS 3200 Martin, Malcolm and America\n",18127 001SEM (3)Wait List (5 / 199) 11 / 20Mar...
16,AAS 3300 Social Science Perspectives on Afric...,19617 001SEM (3)Open 7 / 22Sabrina Pendergrass...
17,AAS 3500 Intermediate Seminar in African-Amer...,12737 001SEM (3)Open 9 / 20Tony PerryTu 3:30pm...
18,AAS 3500 Intermediate Seminar in African-Amer...,12738 002SEM (3)Wait List (2 / 199) 24 / 24Nzi...
19,AAS 3500 Intermediate Seminar in African-Amer...,"18119 003SEM (3)Open, WL (2 / 199) 17 / 20Kimb..."
20,AAS 3500 Intermediate Seminar in African-Amer...,18120 004SEM (3)Wait List (4 / 199) 20 / 20Kim...
21,AAS 3500 Intermediate Seminar in African-Amer...,13099 005SEM (3)Wait List (2 / 199) 15 / 15Pam...
22,AAS 3500 Intermediate Seminar in African-Amer...,12740 006SEM (3)Open 13 / 18Claire PaytonTh 3:...
23,AAS 3500 Intermediate Seminar in African-Amer...,13644 009SEM (3)Open 22 / 30Ethan MadarietaMoW...
24,AAS 3500 Intermediate Seminar in African-Amer...,19876 012SEM (3)Open 9 / 18Brian SmithsonTuTh ...
25,"AAS 3810 Race, Culture and Inequality\n",13100 001SEM (3)Wait List (4 / 199) 19 / 20Sab...
26,"AAS 3830 Being Human: Race, Technology, and t...","19614 001SEM (3)Open, WL (3 / 199) 11 / 24Njel..."
27,AAS 4080 Thesis\n,10008 001IND (3)Permission1 / 10Sabrina Pender...
28,AAS 4080 Thesis\n,20312 002IND (3)Permission0 / 10Njelle Hamilto...
29,AAS 4080 Thesis\n,20313 003IND (3)Permission1 / 10Justene Hill E...
...,...,...
6335,KINE 8999 Master's Thesis\n,14755 6IND (1 - 6)Open0 / 30Joseph HartTBATBA\n
6336,KINE 8999 Master's Thesis\n,14756 7IND (1 - 6)Open0 / 30David EdwardsTBATBA\n
6337,KINE 8999 Master's Thesis\n,14757 8IND (1 - 6)Open0 / 30Barbara BoyceTBATBA\n
6338,KINE 8999 Master's Thesis\n,14761 9IND (1 - 6)Open0 / 30Jacob ReschTBATBA\n
6339,KINE 8999 Master's Thesis\n,18168 010IND (1 - 6)Open0 / 30Jay HertelTBATBA\n
6340,KINE 9740 Internship in College Teaching or S...,14677 1IND (1 - 6)Open2 / 10Barbara BoyceTBATBA\n
6341,KINE 9993 Independent Study\n,14911 11IND (1 - 6)Open4 / 30Jason AllenTBATBA\n
6342,KINE 9998 Doctoral Research Apprenticeship\n,14719 1IND (3 - 12)Open0 / 30Arthur WeltmanTBA...
6343,KINE 9998 Doctoral Research Apprenticeship\n,14720 2IND (3 - 12)Open1 / 30Susan SalibaTBATBA\n
6344,KINE 9998 Doctoral Research Apprenticeship\n,14721 3IND (3 - 12)Open2 / 30Jay HertelTBATBA\n
6345,KINE 9998 Doctoral Research Apprenticeship\n,14722 4IND (3 - 12)Open1 / 30Joseph HartTBATBA\n
6346,KINE 9998 Doctoral Research Apprenticeship\n,14723 5IND (3 - 12)Open0 / 30Luke KellyTBATBA\n
6347,KINE 9998 Doctoral Research Apprenticeship\n,14724 6IND (3 - 12)Open0 / 30David EdwardsTBAT...
6348,KINE 9998 Doctoral Research Apprenticeship\n,14725 7IND (3 - 12)Open0 / 30Martin BlockTBATBA\n
6349,KINE 9998 Doctoral Research Apprenticeship\n,14726 8IND (3 - 12)Open0 / 30Barbara BoyceTBAT...
6350,KINE 9998 Doctoral Research Apprenticeship\n,14727 9IND (3 - 12)Open1 / 30Jacob ReschTBATBA\n
6351,KINE 9998 Doctoral Research Apprenticeship\n,14728 10IND (3 - 12)Open1 / 30Steven MalinTBAT...
6352,KINE 9998 Doctoral Research Apprenticeship\n,14887 11IND (3 - 12)Open0 / 30Sibylle KranzTBA...
6353,KINE 9998 Doctoral Research Apprenticeship\n,15022 012IND (3 - 12)Open 2 / 30Jason AllenTBA...
6354,KINE 9999 Doctoral Dissertation\n,14712 1IND (3 - 12)Open0 / 30Arthur WeltmanTBA...
6355,KINE 9999 Doctoral Dissertation\n,14713 2IND (3 - 12)Open2 / 30Susan SalibaTBATBA\n
6356,KINE 9999 Doctoral Dissertation\n,14714 3IND (3 - 12)Open0 / 30Jay HertelTBATBA\n
6357,KINE 9999 Doctoral Dissertation\n,14715 4IND (3 - 12)Open1 / 30Joseph HartTBATBA\n
6358,KINE 9999 Doctoral Dissertation\n,14716 5IND (3 - 12)Open0 / 30Luke KellyTBATBA\n
6359,KINE 9999 Doctoral Dissertation\n,14717 6IND (3 - 12)Open0 / 30David EdwardsTBAT...
6360,KINE 9999 Doctoral Dissertation\n,14718 7IND (3 - 12)Open0 / 30Barbara BoyceTBAT...
6361,KINE 9999 Doctoral Dissertation\n,14762 8IND (3 - 12)Open0 / 30Martin BlockTBATBA\n
6362,KINE 9999 Doctoral Dissertation\n,14888 9IND (3 - 12)Open0 / 30Sibylle KranzTBAT...
6363,KINE 9999 Doctoral Dissertation\n,14981 010IND (3 - 12)Open1 / 30Jacob ReschTBAT...
6364,KINE 9999 Doctoral Dissertation\n,20638 11IND (3 - 12)Open1 / 30Steven MalinTBAT...

In [90]:
df.to_csv(r"PairedCoursesAndClasses.csv")